In [ ]:
#numpy ndim function

In [4]:
import numpy as np

x=np.array([2,3,4])
print(x.ndim)

1


In [10]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y.ndim)

2


In [17]:
z=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(z.ndim)

3


In [ ]:
# numpy reshape function

In [23]:
import numpy as np

v=np.arange(12)
print(v)

p = np.reshape(v,(3,4))
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
v = np.arange(16)
print(v)

p=np.reshape(v,(4,4))
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# numpy tolist function 

In [2]:
import numpy as np

v = np.array([1,2,3,4,5])
print(v)

p = v.tolist()
print(p)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [5]:
v = np.array([[1,2,3],[4,5,6]])
print(v)

p = v.tolist()
print(p)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [7]:
v = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(v)

p =v.tolist()
print(p)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [ ]:
# numpy nditer function

In [10]:
import numpy as np

v = np.array([1,2,3])
n = np.array([4,5,6])

print(v,n)

for x, y in np.nditer([v,n]):
    print(x,y)



[1 2 3] [4 5 6]
1 4
2 5
3 6


In [12]:
v =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
n =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(v,n)

for x,y in np.nditer([v,n]):
    print(x,y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12


In [ ]:
# numpy ndenumerate function

In [14]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

for index,value in np.ndenumerate(a):
    print(index,value)

[[1 2 3]
 [4 5 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
# numpy flatten function

In [20]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.flatten()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [21]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

b = a.flatten()
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# numpy ravel funnction

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.ravel()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

b = a.ravel()
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Numpy copy function

In [6]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.copy(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Numpy zeros function

In [7]:
import numpy as np

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [9]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.zeros((3,4,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# numpy ones function

In [13]:
import numpy as np

a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [12]:
a =np.ones((3,4))
print (a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
a = np.zeros((3,4,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# Numpy full() function

In [17]:
import numpy as np


a = np.full(5,6)
print(a)

[6 6 6 6 6]


In [16]:
a = np.full((3,3),71)
print(a)


[[71 71 71]
 [71 71 71]
 [71 71 71]]


In [ ]:
# numpy arange() function

In [18]:
import numpy as np

a = np.arange(5)
print(a)

[0 1 2 3 4]


In [20]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
# numpy around() function

In [22]:
import numpy as np

a = np.array([1.2,2.5,3.6,4.1,5.7])
print(a)

b = np.around(a)
print(b)

[1.2 2.5 3.6 4.1 5.7]
[1. 2. 4. 4. 6.]


In [ ]:
# nummpy linspace() function

In [25]:
import numpy as np

a = np.linspace(1,5,10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [30]:
a = np.linspace(1,100,3)
print(a)

[  1.   50.5 100. ]


In [ ]:
#Numpy eye() function

In [31]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
a = np.eye(3,4)
print(a)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [35]:
#Numpy identity() function

In [44]:
import numpy as np

a = np.identity(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Numpy random() function

In [48]:
import numpy as np

a = np.random.random(5)
print(a)

[0.35600337 0.35488226 0.10475424 0.757465   0.39107223]


In [ ]:
# Numpy append() function

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

b=np.append(a,56)
print(b)

[1 2 3]
[ 1  2  3 56]


In [4]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.append(a,b)
print(c)


[1 2 3 4 5 6 7 8]


In [ ]:
# Numpy concatenate() function

In [10]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])


d = np.concatenate((a,b,c))
print(d)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#numpy sort() function

In [11]:
import numpy as np

a = np.array([6,2,3,4,8])

b = np.sort(a)
print(b)

[2 3 4 6 8]


In [ ]:
# NUmpy add() function

In [13]:
import numpy as np

a = np.array([1,2,3])

b = np.add(a,5)
print(b)

[6 7 8]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c=np.add(a,b)
print(c)

[5 7 9]


In [ ]:
# numpy multiply() function

In [16]:
import numpy as np

a = np.array([1,2,3])

b = np.multiply(a,10)
print(b)

[10 20 30]


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c=np.multiply(a,b)
print(c)

[ 4 10 18]


In [ ]:
# numpy dot() function

In [22]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.dot(a,b)
print(c)

32


In [23]:
#numpy floor function

In [24]:
import numpy as np

a = np.array([1.8,2.3,3.5])
print(a)

b = np.floor(a)
print(b)


[1.8 2.3 3.5]
[1. 2. 3.]


In [ ]:
# numpy ceil() function

In [25]:
import numpy as np

a = np.array([1.8,2.2,3.5,8.1])
print(a)

b = np.ceil(a)
print(b)

[1.8 2.2 3.5 8.1]
[2. 3. 4. 9.]


In [ ]:
# numpy sqrt() funntion

In [26]:
import numpy as np

a = np.array([2,4,9,16,17])
print(a)

b = np.sqrt(a)
print(b)

[ 2  4  9 16 17]
[1.41421356 2.         3.         4.         4.12310563]


In [ ]:
# numpy cbrt() function

In [28]:
import numpy as np

a = np.array([8,27,50,64])
print(a)

b = np.cbrt(a)
print(b)

[ 8 27 50 64]
[2.        3.        3.6840315 4.       ]


In [ ]:
# numpy where() function

In [35]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
print(a,b)

condition = np.array([False,False,True,False,True])

c = np.where(condition,a,b)
print(c)

[1 2 3 4 5] [10 20 30 40 50]
[10 20  3 40  5]


In [ ]:
#numpy mean() function

In [40]:
import numpy as np

a = np.array([10,20,30])
print(a)

b = np.mean(a)
print(b)

[10 20 30]
20.0


In [42]:
a = np.array([[1,2,3],[4,5,6]])

b =np.mean(a)
print(b)

3.5


In [ ]:
#numpy median function

In [50]:
import numpy as np

a = np.array([1,2,3,4,5])

b = np.median(a)
print(b)

3.0


In [51]:
# numpy std() function

In [52]:
import numpy as np

a = np.array([1,2,3])

b = np.std(a)
print(b )

0.816496580927726


In [ ]:
# numpy variance() or var() function

In [53]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.var(a)
print(b)

[1 2 3]
0.6666666666666666


In [ ]:
# numpy sin() function

In [56]:
import numpy as np

np.sin(np.pi/2) #180/2 = 90

1.0

In [60]:
np.sin(np.pi/3) #180/3=60

0.8660254037844386

In [58]:
np.sin(np.pi/4) #180/4=45

0.7071067811865476

In [ ]:
# numpy cos() function

In [1]:
import numpy as np

np.cos(np.pi) #180

-1.0

In [2]:
np.cos(np.pi/2) #180/2=90

6.123233995736766e-17

In [3]:
np.cos(np.pi/3) # 60

0.5000000000000001

In [4]:
np.cos(np.pi/4) #45

0.7071067811865476

In [ ]:
# numpy tan() function

In [5]:
np.tan(np.pi) #180

-1.2246467991473532e-16

In [6]:
np.tan(np.pi/2) #90

1.633123935319537e+16

In [7]:
np.tan(np.pi/3) #60 

1.7320508075688767

In [8]:
np.tan(np.pi/4) #45

0.9999999999999999

In [ ]:
#numpy sec() fumction

In [18]:
import numpy as np

sec = 1/np.cos(np.pi)

print(sec)

-1.0

In [19]:
sec = 1/np.cos(np.pi/2) #90
print(sec)

1.633123935319537e+16


In [20]:
sec = 1/np.cos(np.pi/3) #60
print(sec)

1.9999999999999996


In [21]:
sec = 1/np.cos(np.pi/4) #45
print(sec)

1.414213562373095


In [ ]:
#numpy cosec() function

In [26]:
import numpy as np

cosec = 1/np.sin(np.pi) #180

print(cosec)

8165619676597685.0


In [27]:
cosec = 1/np.sin(np.pi/2) #90

print(cosec)

1.0


In [29]:
cosec = 1/np.sin(np.pi/3) #60

print(cosec)

1.1547005383792517


In [31]:
cosec = 1/np.sin(np.pi/4) #45

print(cosec)

1.414213562373095


In [ ]:
# numpy deg2rad() funtion

# Degree to Radian

In [3]:
import numpy as np

deg = 45

a = np.deg2rad(deg)
print(a) 

0.7853981633974483


In [4]:
a = np.array([0,45,60,90])

b = np.deg2rad(a)
print(b)

[0.         0.78539816 1.04719755 1.57079633]


In [5]:
# numpy rad2deg() function

# radian to degree

In [14]:
import numpy as np

a = np.array([0, 0.78539816,1.04719755,1.57079633,np.pi/2])

b = np.rad2deg(a)
b

array([ 0.        , 44.99999981, 59.99999993, 90.00000018, 90.        ])

In [ ]:
#numpy linalg.slove() function

#  2x+3y=10
#  3x+5y=20

#  x=?
#  y=?


In [19]:
import numpy as np

a = np.array([[2,3],[3,5]])
b = np.array([10,20])

c = np.linalg.solve(a,b)
print(c)

[-10.  10.]


In [20]:
# 2x+3y-4z=100
# 3x-8y+9z=200
# 4x+10y-25z=300

# x=?,y=?,z=? 

In [21]:
a = np.array([[2,3,-4],[3,-8,9],[4,10,-25]])

b = np.array([100,200,300])

c = np.linalg.solve(a,b)
c

array([ 54.09836066, -15.40983607,  -9.50819672])

In [ ]:
# numpy linalg.polynomial.Polynomial() 

In [46]:
import numpy as np

eq=np.polynomial.Polynomial([5,-5,1])
eq

Polynomial([ 5., -5.,  1.], domain=[-1,  1], window=[-1,  1], symbol='x')

In [49]:
from numpy.polynomial import Polynomial

a = Polynomial([5,-8,-9])
a

Polynomial([ 5., -8., -9.], domain=[-1,  1], window=[-1,  1], symbol='x')

In [50]:
b = a.roots()
b

array([-1.31224996,  0.42336108])

In [ ]:
# numpy linalg.eigvals() function

In [52]:
a = np.array([[2,3],[4,5]])
b = np.linalg.eigvals(a)
print(b)

[-0.27491722  7.27491722]


In [ ]:
# numpy linalg.eig() function

In [53]:
import numpy as np

a = np.array([[2,3],[4,5]])

eigen_values,eigen_vectors=np.linalg.eig(a)

print(eigen_values)
print(eigen_vectors)

[-0.27491722  7.27491722]
[[-0.79681209 -0.49436913]
 [ 0.60422718 -0.86925207]]


In [54]:
# numpy log() function

In [55]:
a = np.array([1,2,3,4,5])

b = np.log(a)
print(b)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# log2() function

In [62]:
a = np.array([1,2,3,4,16])

b = np.log2(a)
print(b)

[0.        1.        1.5849625 2.        4.       ]


In [63]:
# log10() function

In [64]:
a = np.array([10,100,1000,10000])
b = np.log10(a)
print(b)

[1. 2. 3. 4.]


In [ ]:
# numpy cumsum() function

In [65]:
import numpy as np

a = np.array([10,20,30,40,50])

b = np.sum(a)
print(b)

150


In [66]:
import numpy as np

a = np.array([2,3,4])

b = np.cumsum(a)
print(b)

[2 5 9]


In [69]:
a = np.array([[2,3,4],[4,5,6]])

b = np.cumsum(a)
print(b)

[ 2  5  9 13 18 24]
